import { Metadata } from "next";
export const metadata: Metadata = {
  title: { absolute: "Blog" },
  description: "Generated by Next.js",
};

export default function blog() {
  return <h1>my blog</h1>;
}
